name: Feature request
description: File a feature request
title: "[FEATURE]: "
labels: ["enhancement"]
branch: 'main'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to see?
      description: Please describe the feature you are requesting.
      placeholder: Describe the feature you'd like to see implemented...
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: "Ex. I'm always frustrated when..."
    validations:
      required: false
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your ideal solution...
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What other approaches have you thought about?
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        Links? References? Screenshots? Anything that will give us more context about the feature request!
        
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
