site_name: Stickler

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - tables
  - toc:
      title: On this page
      permalink: false
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
   - search
   - awesome-nav:
        index_page: Getting-Started/README.md  
   - mkdocstrings:
        handlers:
          python:
            paths: [../src]
            options:
              docstring_style: google
              show_root_heading: true
              show_source: true

extra_javascript:
  # Workaround for site_url breaking mermaid rendering; see the following for more info:
  # https://github.com/squidfunk/mkdocs-material/issues/3742#issuecomment-1076068038
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js
  - assets/auto-redirect.js