site_name: Stickler
repo_url: https://github.com/awslabs/stickler
repo_name: awslabs/stickler

theme:
  name: shadcn
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  show_title: true
  show_stargazers: true 
  pygments_style:
        light: shadcn-light
        dark: github-dark
  icon: img/stickler-logo-white-background.svg
  topbar_sections: true
  katex_options:
    macros:
      "\\dx": "\\mathrm{d}x"
  show_datetime: true

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
  pymdownx.blocks.caption:

plugins:
   - search
   - awesome-nav:
        index_page: Getting-Started/README.md  
   - mkdocstrings:
        handlers:
          python:
            paths: [../src]
            options:
              docstring_style: google
              show_root_heading: true
              show_source: true

extra_css:
  - css/custom.css

extra_javascript:
  # Workaround for site_url breaking mermaid rendering; see the following for more info:
  # https://github.com/squidfunk/mkdocs-material/issues/3742#issuecomment-1076068038
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js
